[FEAT] Adds !everyone command & updates command !command
Coding-in-community/alice pull request #44
Opened 2021-08-09 00:06 UTC by EmersonDoAmaral

2021-08-09 22:18 UTC, carlos3g requested changes
@EmersonDoAmaral, acredito que você não entendeu bem o objetivo desse comando e a forma como isso deve ser feito. 
O comando deve apenas marcar todos os usuários com uma mensagem padrão em resposta a uma outra mensagem. Ou seja, ao responder uma mensagem `A` com o comando `!everyone`, uma mensagem marcando todos os membros do grupo vai ser enviada em resposta a mensagem `A` (Veja a imagem de exemplo logo abaixo)

<img src="https://user-images.githubusercontent.com/52337966/128781176-c8126b00-940b-4a49-ba89-2419a9db1667.jpg" alt="imagem de exemplo" width="400px"/>


> Nota 1: coloque a mensagem padrão como '@everyone' (sim, o objetivo disso é ficar parecido com o @overyone do Discord)

> Nota 2: se o comando não responde nenhuma mensagem, lance o erro "No message was replied"

Faça as devidas mudanças e aprovaremos o PR. Muito obrigado pela contribuição, Emerson!

2021-08-10 08:47 UTC, EmersonDoAmaral commented
Coisas importantes a se considerar:
![image](https://user-images.githubusercontent.com/48364166/128829258-4a40baba-5aab-4a6f-b69d-c11bb0ce03fe.png)
Quando `quotedMessage.reply(string, {mentions: participants})` é usado, um erro é lançado. Se usado sem o `{mentions: participants}` tudo ocorre bem.

2021-08-10 14:10 UTC, carlos3g requested changes

2021-08-10 14:10 UTC, carlos3g commented on src/commands/everyone.js
> +      });
Quase lá, Emerson! Só mais uma mudança e o PR será aprovado.

Sempre que possível, para manter o código mais limpo, use `Message.reply` ao invés de `Chat.sendMessage`. O erro que você recebeu ao tentar usar o método `Message.reply` ocorreu porque você estava passando o param `options` no lugar do param `chatId`, para resolver isso é só passar `undefined` no lugar do `chatId`. Os parametros do método podem ser vistos [aqui](https://docs.wwebjs.dev/Message.html#reply)
```suggestion
      quotedMessage.reply(this.strings.defaultMessage, undefined, {
        mentions: participants,
      });
```

2021-08-10 18:32 UTC, EmersonDoAmaral commented on src/commands/everyone.js
> +      });
Ahh, entendi.

2021-08-10 19:20 UTC, carlos3g approved these changes

2021-08-10 19:21 UTC, merged